version: '3.9'

services:
  backend:
    build: ./backend 
    container_name: expense-backend
    ports: 
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    container_name: expense-frontend
    ports:
      - "3000:80"
    restart: unless-stopped